"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { ShieldCheck, Sparkles, AlertCircle, Calendar, FileText, ArrowLeft, Layers, ScanLine, Volume2, Code2, Video, Info } from "lucide-react";
import Background from "@/components/Background";
import Navbar from "@/components/Navbar";
import { CircularProgress } from "@/components/CircularProgress";
import ExplainabilityPanel from "@/components/ExplainabilityPanel";
import { Card, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";

export default function SharePage() {
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;

  const [loading, setLoading] = useState(true);
  const [result, setResult] = useState<any>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;

    const fetchResult = async () => {
      const apiBase = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
      try {
        const response = await fetch(`${apiBase}/detect/results/${id}`);
        if (!response.ok) {
          if (response.status === 404) {
            throw new Error("This verification report does not exist or has expired.");
          }
          throw new Error(`Failed to load report (Status ${response.status})`);
        }
        const data = await response.json();
        setResult(data);
      } catch (err) {
        console.error("Error loading shared scan:", err);
        setErrorMsg(err instanceof Error ? err.message : "An unexpected error occurred.");
      } finally {
        setLoading(false);
      }
    };

    fetchResult();
  }, [id]);

  const getStatusDetails = (score: number, type: string) => {
    let text = "Likely Mixed";
    let color = "text-amber-400";
    let bg = "bg-amber-500";
    let border = "border-amber-500/20";
    let desc = "Linguistic and stylistic analysis shows blended human and AI patterns.";

    if (type === "audio") {
      if (score > 0.6) {
        text = "Likely AI-Generated Voice";
        color = "text-red-400";
        bg = "bg-red-500";
        border = "border-red-500/20";
        desc = "Signal patterns and synthetic speech indicators indicate generated voice audio.";
      } else if (score < 0.4) {
        text = "Likely Human Voice";
        color = "text-emerald-400";
        bg = "bg-emerald-500";
        border = "border-emerald-500/20";
        desc = "Speech prosody and natural variance indicators confirm a human speaker.";
      }
    } else if (type === "code") {
      if (score > 0.6) {
        text = "Likely AI-Generated Code";
        color = "text-red-400";
        bg = "bg-red-500";
        border = "border-red-500/20";
        desc = "Algorithmic patterns and logical structure align heavily with code generated by LLMs.";
      } else if (score < 0.4) {
        text = "Likely Human Code";
        color = "text-emerald-400";
        bg = "bg-emerald-500";
        border = "border-emerald-500/20";
        desc = "Coding style, comment style, and logical flow are highly characteristic of manual programming.";
      }
    } else {
      if (score > 0.6) {
        text = "Likely AI-Generated";
        color = "text-red-400";
        bg = "bg-red-500";
        border = "border-red-500/20";
        desc = "High-confidence structural and stylistic signatures of artificial content generation detected.";
      } else if (score < 0.4) {
        text = "Likely Human Created";
        color = "text-emerald-400";
        bg = "bg-emerald-500";
        border = "border-emerald-500/20";
        desc = "Natural variability, lexical richness, and complexity markers confirm human creation.";
      }
    }

    return { text, color, bg, border, desc };
  };

  const renderSegmentAnalysis = () => {
    if (!result || !result.sentences) return null;

    return (
      <div className="bg-slate-950/50 rounded-xl p-6 font-mono text-sm leading-relaxed text-slate-300 max-h-96 overflow-y-auto border border-white/5 whitespace-pre-wrap custom-scrollbar">
        {result.sentences.map((item: any, idx: number) => {
          const probability = item.ai_probability ?? item.score ?? 0;
          let bgClass = "bg-emerald-500/5";
          let textClass = "text-slate-300";
          let borderClass = "border-transparent";

          if (probability > 0.9) {
            bgClass = "bg-red-500/30";
            textClass = "text-red-50";
            borderClass = "border-red-500/40";
          } else if (probability > 0.7) {
            bgClass = "bg-orange-500/20";
            textClass = "text-orange-50";
            borderClass = "border-orange-500/30";
          } else if (probability > 0.5) {
            bgClass = "bg-amber-500/10";
            textClass = "text-amber-50";
            borderClass = "border-amber-500/20";
          }

          return (
            <span
              key={idx}
              className={`inline-block px-1.5 py-0.5 rounded-md transition-all duration-300 border-b-2 hover:scale-[1.01] cursor-default ${bgClass} ${textClass} ${borderClass}`}
              title={`AI Probability: ${Math.round(probability * 100)}%`}
            >
              {item.text}{" "}
            </span>
          );
        })}
      </div>
    );
  };

  return (
    <>
      <Background />
      <Navbar />

      <main className="relative z-10 min-h-screen flex flex-col items-center justify-center p-4 pt-32 pb-20">
        <div className="w-full max-w-5xl flex flex-col space-y-8">
          
          {/* Header Action */}
          <div className="flex justify-between items-center px-2">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => router.push("/")}
              className="text-slate-400 hover:text-white"
            >
              <ArrowLeft size={16} className="mr-2" />
              Back to Scanner
            </Button>
            <div className="flex items-center space-x-2 text-slate-400 text-xs bg-slate-900/60 border border-white/5 py-1.5 px-3 rounded-full">
              <ShieldCheck size={14} className="text-blue-500" />
              <span className="font-semibold text-blue-400">Verified TrueScan Analysis Result</span>
            </div>
          </div>

          <AnimatePresence mode="wait">
            {loading ? (
              <motion.div
                key="loading"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center justify-center py-40 space-y-4"
              >
                <div className="w-12 h-12 rounded-full border-2 border-t-blue-500 border-r-transparent border-b-transparent border-l-transparent animate-spin" />
                <p className="text-slate-400 text-sm font-light">Retrieving secure verification report...</p>
              </motion.div>
            ) : errorMsg ? (
              <motion.div
                key="error"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
              >
                <Card className="border border-red-500/20 bg-slate-900/60 backdrop-blur-2xl p-10 text-center shadow-2xl">
                  <CardContent className="flex flex-col items-center space-y-6">
                    <div className="w-16 h-16 rounded-full bg-red-500/10 flex items-center justify-center text-red-500">
                      <AlertCircle size={32} />
                    </div>
                    <div className="space-y-2">
                      <h2 className="text-xl font-bold text-white">Report Retrieval Failed</h2>
                      <p className="text-slate-400 text-sm max-w-md mx-auto">{errorMsg}</p>
                    </div>
                    <Button variant="glow" onClick={() => router.push("/")} className="rounded-full px-6">
                      Go to Scanner
                    </Button>
                  </CardContent>
                </Card>
              </motion.div>
            ) : (
              <motion.div
                key="result"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="space-y-6"
              >
                {(() => {
                  const score = result.ai_probability ?? result.score ?? 0.5;
                  const humanScore = 1 - score;
                  const status = getStatusDetails(score, result.type);

                  return (
                    <>
                      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        {/* Left: Verdict Card */}
                        <Card className={`lg:col-span-2 border border-white/10 ${status.border} shadow-2xl relative overflow-hidden group bg-slate-900/60 backdrop-blur-2xl`}>
                          <div className={`absolute inset-0 opacity-5 blur-3xl pointer-events-none rounded-full ${status.bg}`} />
                          
                          <CardContent className="p-8">
                            <div className="flex flex-col md:flex-row items-center gap-10">
                              {/* Gauge */}
                              <div className="relative shrink-0">
                                <CircularProgress 
                                  value={score * 100} 
                                  size={180}
                                  strokeWidth={14}
                                  color={score > 0.6 ? "#ef4444" : score < 0.4 ? "#10b981" : "#f59e0b"}
                                />
                                <div className="absolute inset-0 flex flex-col items-center justify-center">
                                  <span className="text-4xl font-black text-white tracking-tighter">
                                    {Math.round(score * 100)}%
                                  </span>
                                  <span className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mt-1 flex items-center gap-1 group/tooltip relative cursor-help">
                                    Risk Score
                                    <Info size={10} className="text-slate-500 hover:text-blue-400 transition-colors" />
                                    <span className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 p-3 bg-slate-950/95 border border-white/10 rounded-xl text-[10px] text-slate-400 normal-case tracking-normal opacity-0 group-hover/tooltip:opacity-100 transition-all duration-300 pointer-events-none z-50 shadow-2xl backdrop-blur-md translate-y-2 group-hover/tooltip:translate-y-0 leading-relaxed text-center font-normal">
                                      <strong>AI Probability / Risk Score</strong> represents the likelihood that this content was generated by an artificial intelligence model (like ChatGPT, Claude, or Midjourney) rather than a human.
                                      <span className="absolute top-full left-1/2 -translate-x-1/2 -mt-2 border-8 border-transparent border-t-slate-950/95" />
                                    </span>
                                  </span>
                                </div>
                              </div>

                              <div className="flex-1 space-y-6 text-center md:text-left w-full">
                                <div>
                                  <h3 className="text-xs font-bold uppercase tracking-widest text-slate-500 mb-1 flex items-center justify-center md:justify-start gap-2">
                                    <FileText size={12} className="text-blue-500" />
                                    {result.filename ? `${result.type.toUpperCase()} SCAN: ${result.filename}` : `${result.type.toUpperCase()} SCAN`}
                                  </h3>
                                  <div className={`text-4xl font-bold tracking-tight ${status.color}`}>
                                    {status.text}
                                  </div>
                                  {result.predicted_source && (
                                    <div className="mt-2 inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-slate-800 border border-white/10 text-xs font-bold text-slate-300">
                                      <Sparkles size={12} className="text-blue-400" />
                                      <span>Predicted Source: <span className="text-white">{result.predicted_source}</span></span>
                                    </div>
                                  )}
                                  <p className="text-slate-400 mt-2 text-sm max-w-md">{status.desc}</p>
                                </div>

                                {/* Confidence Bars */}
                                <div className="space-y-4 w-full max-w-md">
                                  <div className="space-y-1">
                                    <div className="flex justify-between text-xs font-bold uppercase tracking-wider text-slate-400">
                                      <span className="flex items-center gap-1 group/bar relative cursor-help">
                                        Risk Probability
                                        <Info size={11} className="text-slate-500 hover:text-blue-400 transition-colors" />
                                        <span className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 p-3 bg-slate-950/95 border border-white/10 rounded-xl text-[10px] text-slate-400 normal-case tracking-normal opacity-0 group-hover/bar:opacity-100 transition-all duration-300 pointer-events-none z-50 shadow-2xl backdrop-blur-md translate-y-2 group-hover/bar:translate-y-0 leading-relaxed font-normal">
                                          <strong>AI Probability Risk Levels:</strong><br />
                                          • <strong>&lt; 40%:</strong> Likely human-created.<br />
                                          • <strong>40% - 60%:</strong> Uncertain/mixed.<br />
                                          • <strong>&gt; 60%:</strong> High likelihood of AI origin.
                                          <span className="absolute top-full left-1/2 -translate-x-1/2 -mt-2 border-8 border-transparent border-t-slate-950/95" />
                                        </span>
                                      </span>
                                      <span>{Math.round(score * 100)}%</span>
                                    </div>
                                    <div className="h-2 bg-slate-900/50 rounded-full overflow-hidden border border-white/5">
                                      <motion.div initial={{ width: 0 }} animate={{ width: `${score*100}%` }} className="h-full bg-gradient-to-r from-red-600 to-red-400 rounded-full" />
                                    </div>
                                  </div>

                                  <div className="space-y-1">
                                    <div className="flex justify-between text-xs font-bold uppercase tracking-wider text-slate-400">
                                      <span>Authenticity Probability</span>
                                      <span>{Math.round(humanScore * 100)}%</span>
                                    </div>
                                    <div className="h-2 bg-slate-900/50 rounded-full overflow-hidden border border-white/5">
                                      <motion.div initial={{ width: 0 }} animate={{ width: `${humanScore*100}%` }} className="h-full bg-gradient-to-r from-emerald-600 to-emerald-400 rounded-full" />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>

                            {/* Metadata */}
                            <div className="mt-8 pt-6 border-t border-white/5 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500">
                              <span className="flex items-center gap-1.5"><Calendar size={13} /> Scanned on: {result.created_at ? new Date(result.created_at).toLocaleString() : "Unknown"}</span>
                              {result.length !== undefined && result.length > 0 && <span>Length: <b className="text-slate-400">{result.length} characters</b></span>}
                              {result.model && <span>Engine: <b className="text-slate-400">{result.model}</b></span>}
                            </div>
                          </CardContent>
                        </Card>

                        {/* Right: Deep Analysis Panel */}
                        <div className="lg:col-span-1 h-full">
                          <ExplainabilityPanel aiScore={score} metrics={result.metrics} />
                        </div>

                        {/* Heatmap (for Image Tab results) */}
                        {result.type === "image" && result.heatmap && (
                          <Card className="lg:col-span-3 border border-white/10 bg-slate-900/60 backdrop-blur-2xl">
                            <CardContent className="p-8">
                              <div className="flex items-center space-x-2 mb-6">
                                <Layers size={18} className="text-blue-500" />
                                <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400">Visual Attribution Map</h3>
                              </div>
                              <div className="relative rounded-2xl overflow-hidden border border-white/10 max-w-2xl mx-auto shadow-2xl">
                                <img 
                                  src={`data:image/jpeg;base64,${result.heatmap}`} 
                                  alt="AI Artifact Heatmap" 
                                  className="w-full h-auto"
                                />
                                <div className="absolute bottom-4 left-4 right-4 bg-black/60 backdrop-blur-md p-3 rounded-xl border border-white/5 text-[10px] text-slate-400 leading-relaxed">
                                  Heatmap highlights regions with high-frequency anomalies and structural inconsistencies typical of AI generation (GAN/Diffusion artifacts).
                                </div>
                              </div>
                            </CardContent>
                          </Card>
                        )}

                        {/* Segment Analysis (for text-based scans) */}
                        {result.type !== "image" && result.type !== "video" && result.type !== "audio" && (
                          <Card className="lg:col-span-3 border border-white/10 bg-slate-900/60 backdrop-blur-2xl">
                            <CardContent className="p-8">
                              <div className="flex items-center space-x-2 mb-6">
                                <ScanLine size={18} className="text-blue-500" />
                                <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400">Detailed Segment Analysis</h3>
                              </div>
                              {renderSegmentAnalysis()}
                            </CardContent>
                          </Card>
                        )}

                        {/* Audio signals panel */}
                        {result.type === "audio" && result.signals && (
                          <Card className="lg:col-span-3 border border-white/10 bg-slate-900/60 backdrop-blur-2xl">
                            <CardContent className="p-8">
                              <div className="flex items-center space-x-2 mb-6">
                                <Volume2 size={18} className="text-green-500" />
                                <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400">Audio Signal Analysis</h3>
                              </div>
                              <div className="space-y-3">
                                {result.signals.map((s: any, i: number) => (
                                  <div key={i} className={`flex items-center gap-3 p-3 rounded-xl border ${s.ai ? 'bg-red-500/5 border-red-500/20' : 'bg-emerald-500/5 border-emerald-500/20'}`}>
                                    <div className={`w-2 h-2 rounded-full shrink-0 ${s.ai ? 'bg-red-400' : 'bg-emerald-400'}`} />
                                    <span className="text-sm text-slate-300 flex-1">{s.signal}</span>
                                    <span className={`text-xs font-bold uppercase px-2 py-0.5 rounded ${s.weight === 'high' ? 'bg-red-500/20 text-red-400' : 'bg-slate-700 text-slate-400'}`}>{s.weight}</span>
                                  </div>
                                ))}
                              </div>
                              {result.audio_stats && (
                                <div className="mt-6 pt-4 border-t border-white/5 flex gap-6 text-xs text-slate-500">
                                  {result.audio_stats.duration_s && <span>Duration: <b className="text-slate-300">{result.audio_stats.duration_s}s</b></span>}
                                  {result.audio_stats.sample_rate && <span>Sample rate: <b className="text-slate-300">{result.audio_stats.sample_rate}Hz</b></span>}
                                  {result.audio_stats.size_kb && <span>Size: <b className="text-slate-300">{result.audio_stats.size_kb}KB</b></span>}
                                </div>
                              )}
                            </CardContent>
                          </Card>
                        )}

                        {/* Code signals panel */}
                        {result.type === "code" && result.signals && (
                          <Card className="lg:col-span-3 border border-white/10 bg-slate-900/60 backdrop-blur-2xl">
                            <CardContent className="p-8">
                              <div className="flex items-center space-x-2 mb-4">
                                <Code2 size={18} className="text-pink-500" />
                                <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400">Code Pattern Analysis</h3>
                                {result.language && <span className="ml-auto text-xs bg-pink-500/10 text-pink-300 px-2 py-0.5 rounded font-mono">{result.language}</span>}
                              </div>
                              <div className="space-y-3 mb-6">
                                {result.signals.map((s: any, i: number) => (
                                  <div key={i} className={`flex items-center gap-3 p-3 rounded-xl border ${s.ai ? 'bg-red-500/5 border-red-500/20' : 'bg-emerald-500/5 border-emerald-500/20'}`}>
                                    <div className={`w-2 h-2 rounded-full shrink-0 ${s.ai ? 'bg-red-400' : 'bg-emerald-400'}`} />
                                    <span className="text-sm text-slate-300 flex-1">{s.signal}</span>
                                    <span className={`text-xs font-bold uppercase px-2 py-0.5 rounded ${s.weight === 'high' ? 'bg-red-500/20 text-red-400' : 'bg-slate-700 text-slate-400'}`}>{s.weight}</span>
                                  </div>
                                ))}
                              </div>
                              {result.code_stats && (
                                <div className="flex gap-6 text-xs text-slate-500 pt-4 border-t border-white/5">
                                  <span>Lines: <b className="text-slate-300">{result.code_stats.lines}</b></span>
                                  <span>Functions: <b className="text-slate-300">{result.code_stats.functions}</b></span>
                                  <span>Comments: <b className="text-slate-300">{result.code_stats.comment_lines}</b></span>
                                </div>
                              )}
                            </CardContent>
                          </Card>
                        )}

                        {/* Video signals panel */}
                        {result.type === "video" && result.signals && (
                          <Card className="lg:col-span-3 border border-white/10 bg-slate-900/60 backdrop-blur-2xl">
                            <CardContent className="p-8">
                              <div className="flex items-center space-x-2 mb-6">
                                <Video size={18} className="text-cyan-400" />
                                <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400">Video Motion & Artifact Analysis</h3>
                              </div>
                              <div className="space-y-3">
                                {result.signals.map((s: any, i: number) => (
                                  <div key={i} className={`flex items-center gap-3 p-3 rounded-xl border ${s.ai ? 'bg-red-500/5 border-red-500/20' : 'bg-emerald-500/5 border-emerald-500/20'}`}>
                                    <div className={`w-2 h-2 rounded-full shrink-0 ${s.ai ? 'bg-red-400' : 'bg-emerald-400'}`} />
                                    <span className="text-sm text-slate-300 flex-1">{s.signal}</span>
                                    <span className={`text-xs font-bold uppercase px-2 py-0.5 rounded ${s.weight === 'high' ? 'bg-red-500/20 text-red-400' : 'bg-slate-700 text-slate-400'}`}>{s.weight}</span>
                                  </div>
                                ))}
                              </div>
                              {result.video_stats && (
                                <div className="mt-6 pt-4 border-t border-white/5 flex gap-6 text-xs text-slate-500">
                                  {result.video_stats.duration_s !== undefined && <span>Duration: <b className="text-slate-300">{result.video_stats.duration_s}s</b></span>}
                                  {result.video_stats.fps !== undefined && <span>FPS: <b className="text-slate-300">{result.video_stats.fps}</b></span>}
                                </div>
                              )}
                            </CardContent>
                          </Card>
                        )}
                      </div>

                      {/* Call To Action */}
                      <div className="flex flex-col items-center justify-center pt-16 pb-8 space-y-6">
                        <div className="text-center space-y-2 max-w-sm">
                          <h4 className="text-lg font-bold text-white">Want to analyze your own content?</h4>
                          <p className="text-xs text-slate-400 leading-relaxed">
                            TrueScan provides military-grade multi-modal AI detection for texts, documents, code, images, audio, and video files.
                          </p>
                        </div>
                        <Button
                          onClick={() => router.push("/")}
                          variant="glow"
                          className="rounded-full px-10 py-5 h-auto text-base shadow-[0_0_30px_rgba(59,130,246,0.3)]"
                        >
                          Try TrueScan Scanner Free
                        </Button>
                      </div>
                    </>
                  );
                })()}
              </motion.div>
            )}
          </AnimatePresence>

        </div>
      </main>
    </>
  );
}
